server:
  port: 8085

spring:
  datasource:
    #    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./data/employees
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

loader:
  feedresource: file:./upstream/feed.csv