CREATE TABLE IF NOT EXISTS EMPLOYEE (
  EMAIL VARCHAR(250) NOT NULL PRIMARY KEY,
  IS_ACTIVE NUMBER
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_AUTHORITY (
  EMAIL VARCHAR(250) NOT NULL,
  AUTHORITY VARCHAR(100) NOT NULL,
  FOREIGN KEY (EMAIL) REFERENCES EMPLOYEE(EMAIL)
);

CREATE UNIQUE INDEX IF NOT EXISTS EMP_AUTH_IDX ON EMPLOYEE_AUTHORITY(EMAIL, AUTHORITY);


